Group Management
AY2324S2-CS2113-T15-1/tp pull request #89
Opened 2024-04-01 13:47 UTC by djleong01

Features Done:

- prompt group creation upon initial startup
- default to first group in list upon subsequent startups
- storing of group names in a txt file
- ability to add new groups (add group <GROUP_NAME>
- ability to switch between existing groups (switchgroup <GROUP_NAME>
- handling of some common errors/execeptions

Yet to be implemented:

- group deletion
- UG/DG

2024-04-01 13:53 UTC, djleong01 commented on src/main/java/longah/exception/ExceptionMessage.java
> +    INVALID_SWITCH_GROUP_COMMAND ("Invalid command format." +
ah minor boohoo, should be " Use 'switchgroup GROUP_NAME' "

2024-04-01 13:54 UTC, djleong01 commented on src/main/java/longah/exception/ExceptionMessage.java
> +            " Use 'switch GROUP_NAME'", ExceptionType.INFO);
ah minor boohoo, should be " Use 'switchgroup GROUP_NAME' "

2024-04-01 14:00 UTC, jing-xiang commented on src/main/java/longah/LongAh.java
> +            new GroupListHandler();
noice

2024-04-01 14:02 UTC, jing-xiang commented on src/main/java/longah/commands/delete/DeleteGroupCommand.java
> +        //group.deleteGroup();
comment intended?

2024-04-01 14:05 UTC, jing-xiang commented on src/main/java/longah/handler/GroupListHandler.java
> +                groupList.addGroup(newGroup);
might want to make use of logger

2024-04-01 14:05 UTC, jing-xiang commented on src/main/java/longah/handler/InputHandler.java
> +        case "switchgroup":
wait the command is switchgroup? like no space?

2024-04-01 14:07 UTC, 1simjustin requested changes
Some changes!

2024-04-01 14:07 UTC, 1simjustin commented on src/main/java/longah/handler/GroupListHandler.java
> +            throw new RuntimeException(e);
All exceptions to run with program implemented exceptions

2024-04-01 14:07 UTC, 1simjustin commented on src/main/java/longah/handler/GroupListHandler.java
> +            UI.showMessage("Error saving group list.");
As above

2024-04-01 14:07 UTC, 1simjustin commented on src/main/java/longah/handler/GroupListHandler.java
> +    public static void printGroupList() {
For ease of testing, have this method return the expected string instead of directly printing

2024-04-01 14:07 UTC, 1simjustin commented on src/main/java/longah/handler/GroupListHandler.java
> +            FileWriter fw = new FileWriter(GROUP_LIST_FILE_PATH, true);
For purpose of delete in the future, might be better to do this in a separate method which does not rely on append.

2024-04-01 14:07 UTC, 1simjustin commented on src/main/java/longah/handler/InputHandler.java
> +        case "switchgroup":
i thnk can just keep to `group`. Im trying to use human readable commands where possible

2024-04-01 14:07 UTC, 1simjustin commented on src/main/java/longah/handler/GroupListHandler.java
Are we not able to have all these methods go in `GroupList`

2024-04-01 14:07 UTC, 1simjustin commented on src/main/java/longah/handler/GroupListHandler.java
> +            for (String groupName : data) {
What happens if `String[] data` is empty

2024-04-01 14:07 UTC, jing-xiang commented on src/main/java/longah/util/GroupList.java
> +    public void removeGroup(Group group) {
whats the diff between this and deletegroup

2024-04-02 04:18 UTC, 1simjustin commented on src/main/java/longah/commands/delete/DeleteGroupCommand.java
> +        UI.showMessage("Deleting group: " + this.taskExpression);
Print after completion so the text will not be shown on exception thrown

2024-04-02 04:18 UTC, 1simjustin commented on src/main/java/longah/util/GroupList.java
> +    private static Group activeGroup;
Set this to NULL initially to prevent unexpected behaviours

2024-04-02 04:18 UTC, 1simjustin commented on src/main/java/longah/util/GroupList.java
> +            throw new LongAhException(ExceptionMessage.IO_EXCEPTION);
Got the `STORAGE_FILE_CORRUPTED` message you could use

2024-04-02 04:18 UTC, 1simjustin commented on src/main/java/longah/util/GroupList.java
> +            getGroupList();
What does this do here?

2024-04-02 04:18 UTC, 1simjustin commented on src/main/java/longah/util/GroupList.java
> +        // did not use exceptions here as I want to return an empty string
If list is empty it will throw the IO exception though, might want to add a return statement after showing empty list message.

2024-04-02 04:18 UTC, 1simjustin commented on src/main/java/longah/util/GroupList.java
> +            UI.showMessage("Group folder deleted.");
Shouldn't have this as a user facing message

2024-04-02 04:18 UTC, 1simjustin commented on src/main/java/longah/util/GroupList.java
> +        return null;
Use exceptions for this

2024-04-02 04:18 UTC, 1simjustin commented on src/main/java/longah/util/GroupList.java
> +        if (group == null) {
Exception handling within `getGroup` would be better

2024-04-02 04:18 UTC, 1simjustin commented on src/main/java/longah/util/GroupList.java
> +    public static void deleteGroup(String groupName) throws LongAhException {
What is behaviour if user deletes the Group they are in?

2024-04-02 09:08 UTC, djleong01 commented
Cleaned up most of the review comments, to add details to DG and some Junit tests

2024-04-02 15:53 UTC, merged